name: build

on:
  push:
    branches: [ 'main' ]
    tags: [ '*' ]
  pull_request:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.10

      - name: Install pipenv
        run: pip install pipenv

      - name: Lint
        run: _CI/scripts/lint.py

      - name: Test
        run: _CI/scripts/test.py

      - name: Build
        run: _CI/scripts/build.py

      - name: Upload built package
        uses: actions/upload-artifact@v3
        with:
          name: awsenergylabelercli-latest
          path: dist/awsenergylabelercli-*.tar.gz

  release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.10

      - name: Install pipenv
        run: pip install pipenv

      - name: Upload
        run: _CI/scripts/upload.py

        env:

          PYPI_UPLOAD_USERNAME: ${{ secrets.PYPI_UPLOAD_USERNAME }}
          PYPI_UPLOAD_PASSWORD: ${{ secrets.PYPI_UPLOAD_PASSWORD }}

  container_release:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: awsenergylabelercli-latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Login to Amazon ECR Private
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Get version
        run: echo "RELEASE_VERSION=`cat .VERSION`" >> $GITHUB_ENV

      - name: Rename tarball
        run: mv awsenergylabelercli-${RELEASE_VERSION}.tar.gz awsenergylabelercli.tar.gz

      - name: Build docker image
        run:  docker build -t awsenergylabelercli .
      
      - name: Tag and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: awsenergylabelercli
        run: |
          docker tag awsenergylabelercli ${REGISTRY}/${REPOSITORY}:${RELEASE_VERSION}
          docker tag awsenergylabelercli ${REGISTRY}/${REPOSITORY}:latest
          docker push ${REGISTRY}/${REPOSITORY}:${RELEASE_VERSION}
          docker push ${REGISTRY}/${REPOSITORY}:latest
